### ISSUE TITLE
Microbic code improvements

### ISSUE THREAD

**Issue by rafaelrinaldi** [tholman/palettab#2]
Hey Tim. First of all congrats to you and Claudio for the very cool project! I'm really diggin' it!

I was taking a look at the code and I would suggest just a few changes in order to improve it or maybe just to share a few tricks with you:

**Better `for` loops**

In `site.js` you have the following:

```js
var i = 0;
for( i; i < colors.length; i++ ) {
  // ...
}
```

Since you're declaring the value of your iterator `i` before the loop, it's fine to omit it from the loop initialization:

```js
var i = 0;
for( ; i < colors.length; i++ ) {
  // I saved Tim a byte!
}
```

I would also recommend caching values that you use in loop conditions because they will be checked in each loop iteration.

```js
var i = 0,
    totalColors = colors.length;
for( ; i < totalColors; i++ ) {
  // such improvement w0w
}
```

**Vendor prefixes**

I see you have a few SCSS mixins to deal with [transform](http://caniuse.com/#search=transform) and [transition](http://caniuse.com/#search=transition). Both have very solid browser support these days so you can remove (almost all of) them:

```scss
@mixin transitionDelay( $duration ) {
  -ms-transition-delay: $duration; // IE9+
  transition-delay: $duration;
}

@mixin transition( $options ) {
  -ms-transition: $options;
  transition: $options;
}

@mixin transformTransition( $options ) {
  -ms-transition: transform $options;
  transition: transform $options;
}

// No need to use this guy, leaving it here to illustrate the diff
@mixin transform( $options ) {
  transform: $options;
}
```

**Font smoothing**

The core of the project is typography, so it must be well rendered. I see you are wisely using `-webkit-font-smoothing` with antialias on for that, I would add another property to make it look nice also in Firefox. Since the ~25 version of the browser there's a property called `-moz-osx-font-smoothing` that you can use. The equivalent of `antialiased` is `grayscale` and the equivalent of `subpixel-antialiased` is `auto`. I would suggest a mixin to deal with this:

```scss
// Fonts ¯\_(ツ)_/¯
@mixin font-smoothing {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

That's it. Hope it helps to improve the project in some way. Let me know if you're ok with that, it would be a pleasure to send you a PR with all these changes :wink:
